In [ ]:
import pandas as pd
import numpy as np

#Construye visualizaciones base
import matplotlib.pyplot as mpt

#Visualizar estadisticas de alto nivel
import seaborn as sns

#Herramienta de escalado estandar 
from sklearn.preprocessing import StandardScaler

from sqlalchemy import create_engine

print("OK")

OK

In [ ]:
df_crudo=pd.read_csv("ventas_techventas.csv",
    encoding="latin1",
    parse_dates=["fecha"])
df_crudo.head()

,order_id,fecha,cliente_id,cliente_nombre,region,producto,categoria,cantidad,precio_unitario,descuento,vendedor
0,1001,2024-01-05,C001,TechCorp SA,Norte,Laptop Pro 15,Electronica,2.0,1200.0,0.10,Ana Lï¿½ï¿
1,1002,2024-01-07,C002,Innovatek,Sur,Mouse Inalambrico,Perifericos,15.0,25.0,0.00,Carlos Ruiz
2,"1003,2024-01-10,C003,DataSolutions,Centro,Moni...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1004,2024-01-12,C001,TechCorp SA,Norte,Teclado Mecanico,Perifericos,10.0,85.0,0.10,Luis Mora
4,1005,2024-01-15,C004,CloudNet,Este,Laptop Pro 15,Electronica,3.0,1200.0,0.15,Carlos Ruiz

# Primeros datos "Incorrectos": 
-order_id-cliente_id- Cantidad Cambiar a INT

-Fecha, debe ser en dataTime

-11 nulos en cada categoria

In [ ]:
df_crudo.info()
df_crudo.describe().round(0)

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         60 non-null     str
 1   fecha            49 non-null     datetime64[us]
 2   cliente_id       49 non-null     str
 3   cliente_nombre   49 non-null     str
 4   region           49 non-null     str
 5   producto         48 non-null     str
 6   categoria        49 non-null     str
 7   cantidad         49 non-null     float64
 8   precio_unitario  49 non-null     float64
 9   descuento        49 non-null     float64
 10  vendedor         49 non-null     str
dtypes: datetime64[us](1), float64(3), str(7)
memory usage: 5.3 KB

                            fecha  cantidad  precio_unitario  descuento
count                          49      49.0             49.0       49.0
mean   2024-03-27 02:26:56.326530      11.0            385.0        0.0
min           2024-01-05 00:00:00      -1.0             25.0        0.0
25%           2024-02-15 00:00:00       3.0             85.0        0.0
50%           2024-03-25 00:00:00       8.0             95.0        0.0
75%           2024-05-07 00:00:00      18.0           1200.0        0.0
max           2024-06-15 00:00:00      35.0           1200.0        0.0
std                           NaN       9.0            497.0        0.0

In [ ]:
nulosTotales= df_crudo.isnull().sum()
nulosTotales

order_id            0
fecha              11
cliente_id         11
cliente_nombre     11
region             11
producto           12
categoria          11
cantidad           11
precio_unitario    11
descuento          11
vendedor           11
dtype: int64

In [ ]:
duplicadosTotales=df_crudo.duplicated().sum()
duplicadosTotales

np.int64(0)

## Lugares exactos que tienen nulos:

In [ ]:
print("nulos por fecha: ")
df_crudo[df_crudo["fecha"].isnull()]

nulos por fecha:

,order_id,fecha,cliente_id,cliente_nombre,region,producto,categoria,cantidad,precio_unitario,descuento,vendedor
2,"1003,2024-01-10,C003,DataSolutions,Centro,Moni...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"1007,2024-01-20,C002,Innovatek,Sur,Monitor 27""...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"1011,2024-02-02,C001,TechCorp SA,Norte,Monitor...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,"1017,2024-02-18,C006,NetPrime,Norte,Monitor 27...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,"1024,2024-03-10,C010,DeltaOps,Norte,Monitor 27...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,"1031,2024-03-28,C003,DataSolutions,Centro,Moni...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,"1036,2024-04-12,C005,Sistemas Globales,Oeste,M...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,"1039,2024-04-20,C002,Innovatek,Sur,Monitor 27""...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,"1051,2024-05-22,C009,GammaDevs,Oeste,Monitor 2...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,"1055,2024-06-04,C004,CloudNet,Este,Monitor 27""...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,"1060,2024-06-18,C008,BetaSoft,Centro,Monitor 2...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print("nulos por prodfucto")
df_crudo[df_crudo["producto"].isnull()]

nulos por prodfucto

,order_id,fecha,cliente_id,cliente_nombre,region,producto,categoria,cantidad,precio_unitario,descuento,vendedor
2,"1003,2024-01-10,C003,DataSolutions,Centro,Moni...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"1007,2024-01-20,C002,Innovatek,Sur,Monitor 27""...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"1011,2024-02-02,C001,TechCorp SA,Norte,Monitor...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,"1017,2024-02-18,C006,NetPrime,Norte,Monitor 27...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,"1024,2024-03-10,C010,DeltaOps,Norte,Monitor 27...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,"1031,2024-03-28,C003,DataSolutions,Centro,Moni...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,"1036,2024-04-12,C005,Sistemas Globales,Oeste,M...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,"1039,2024-04-20,C002,Innovatek,Sur,Monitor 27""...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,1043,2024-05-01,C010,DeltaOps,Norte,NaN,Electronica,2.0,350.0,0.05,Maria Torres
50,"1051,2024-05-22,C009,GammaDevs,Oeste,Monitor 2...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,"1055,2024-06-04,C004,CloudNet,Este,Monitor 27""...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,"1060,2024-06-18,C008,BetaSoft,Centro,Monitor 2...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Tratamiento de nulos:

In [ ]:
df_copia= df_crudo.copy()

df_copia["fecha"] = pd.to_datetime(df_copia["fecha"], errors="coerce")

df_copia["anio"]          = df_copia["fecha"].dt.year
df_copia["mes"]           = df_copia["fecha"].dt.month
df_copia["dia"]           = df_copia["fecha"].dt.day
df_copia["nombre_mes"]    = df_copia["fecha"].dt.month_name()
df_copia["dia_semana"]    = df_copia["fecha"].dt.day_name()
df_copia["trimestre"]     = df_copia["fecha"].dt.quarter

df_copia[["fecha", "anio", "mes", "nombre_mes", "dia", "dia_semana", "trimestre"]].head(8)

       fecha    anio  mes nombre_mes   dia dia_semana  trimestre
0 2024-01-05  2024.0  1.0    January   5.0     Friday        1.0
1 2024-01-07  2024.0  1.0    January   7.0     Sunday        1.0
2        NaT     NaN  NaN        NaN   NaN        NaN        NaN
3 2024-01-12  2024.0  1.0    January  12.0     Friday        1.0
4 2024-01-15  2024.0  1.0    January  15.0     Monday        1.0
5 2024-01-18  2024.0  1.0    January  18.0   Thursday        1.0
6        NaT     NaN  NaN        NaN   NaN        NaN        NaN
7 2024-01-22  2024.0  1.0    January  22.0     Monday        1.0

In [ ]:
df_copia["order_id"]=df_copia["order_id"].astype()
df_copia["cliente_id"]=df_copia["cliente_id"].astype(int)
df_copia["cantidad"]=df_copia["cantidad"].astype(int)

ValueError: invalid literal for int() with base 10: '1003,2024-01-10,C003,DataSolutions,Centro,Monitor 27",Electronica,5,350.00,0.05,Ana Lï¿½ï¿'